### PR TITLE
fix: Revise One Call API to version 3.0

### PR DESCRIPTION
**Pull request by LeoBley**
Version 2.5 One Call API call returns an error 401

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Revise One Call API to version 3.0
**Which issue (if any) does this pull request address?**
Version 2.5 One Call API call returns an error 401
**Is there anything you'd like reviewers to focus on?**
Test current call with master's "/2.5/" API call to verify 401 error, then test with "/3.0/" to verify fix.

### CODE REVIEW

**Comment by LeoBley** [comment]
Thanks Mike

I’m trying out the OpenWeather API template integration… Thanks!

Have you seen anyone convert their `icon` or `description` key values into emoji like web.weather() uses?

Leo Bley

h: +1.408.300.4231
h: ***@***.***

**Comment by mikeerickson** [comment]
You should reach out to @dwertheimer as he is the one who created this example, I don’t use it myself.

**Comment by LeoBley** [comment]
Sorry, I think I saw that contribution attribution. Thanks for the lead. 

Leo Bley

h: +1.408.300.4231
h: ***@***.***

**Comment by dwertheimer** [comment]
UPDATE: @LeoBley I now see the code in your commit. You are, in fact commenting on a np.Templating example in the np.Templating docs rather than any of the stuff I said below. So, I actually do think this is a question for @mikeerickson to look at when he has time.

...my original response (with some background which may not be relevant)...
@LeoBley I'm just seeing this now. When you say "OpenWeather API template integration", what exactly are you referring to? OpenWeather used to be the standard in nmn.Templates a long time ago. Is that what you're referring to? It was replaced by web.weather when @mikeerickson wrote np.Templating because it pulls weather by IP address and requires nothing from a user (no setting up API keys, etc.). I missed some of the functionality of OpenWeather, did some work on a Weather plugin awhile back (in the repo at np.WeatherLookup) but I didn't finish it. So there's a lot of weather stuff out there. Which of these are you referring to?

**Comment by LeoBley** [comment]
Hi David,

Thanks for your prior work. There was an example of using OpenWeather’s One Call API to get a weather feed specific to an absolute lat/long instead of web.weather’s IP resolution that gets obfuscated if you use a VPN (which is not geographically resolvable in my case, and potentially not accurate / relevant for others). 

I get the default’s simplicity. In my case I need the openweather api’s locale specificity, but the encoded api call was for a non-supported version (2.5), so I created a PR to upgrade it to their 3.0 call. 

I do, however, wonder if you figured out a way to map their weather description / icon JSON key value to an emoji like web.weather uses. 

Leo Bley

h: +1.408.300.4231
h: ***@***.***

**Comment by dwertheimer** [comment]
@LeoBley w/r/t the icons, there may be some code here that could be useful to you.
https://github.com/NotePlan/plugins/blob/21c3198476d2694dc913d777a1247e193d0cd919/np.WeatherLookup/src/support/weather-utils.js#L72

BTW, if you know Javascript, you could probably help finish that plugin and then you could call it from within a template. :)

**Pull request closed without merging**
